
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: awaits.await.argoproj.io
spec:
  group: await.argoproj.io
  names:
    kind: Await
    plural: awaits
  scope: ""
  validation:
    openAPIV3Schema:
      description: Await is the Schema for the awaits API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AwaitSpec defines the desired state of Await
          properties:
            filters:
              items:
                type: string
              type: array
            resource:
              description: Resource defines the Resource to be awaited
              properties:
                group:
                  type: string
                kind:
                  type: string
                name:
                  description: name is the plural name of the resource.
                  type: string
                version:
                  type: string
              required:
              - kind
              - name
              type: object
            workflow:
              description: NamespacedWorkflow defines the workflow to be resumed
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
              - name
              - namespace
              type: object
          required:
          - resource
          - workflow
          type: object
        status:
          description: AwaitStatus defines the observed state of Await
          properties:
            finishedAt:
              format: date-time
              type: string
            startedAt:
              format: date-time
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
